### ISSUE TITLE
Sort Homeless people by last edit profile 

### ISSUE THREAD

**Issue by AllanBallester** [AllanBallester/RiSE#138]

**Comment by AllanBallester** [comment]
Celine and Michel (example in Lille location) are the last homeless we helped however they are very down on the result page. We should prioritize profiles based on any action is done on them :

- Created
- Profile edited
- Review given

<img width="1400" alt="Screenshot 2019-10-07 at 11 52 03" src="https://user-images.githubusercontent.com/17672429/66302350-0f238e80-e8f9-11e9-9350-9f5f5727bae1.png">

**Comment by AllanBallester** [comment]
<img width="1156" alt="Screenshot 2019-11-24 at 18 50 4@pel-daniel " src="https://user-images.githubusercontent.com/17672429/69498773-df056e80-0eeb-11ea-87d8-d6e993e40305.png">

@pel-daniel do you get time to help me sort that ?

**Comment by pel-daniel** [comment]
A simple solution is to add `order` in `HomelessController` line 5
```
@homelesses = Homeless.includes(:position_histories).near(params[:location], 10).order(updated_at: :desc)
```

It doesn't consider `Review given`, only `Profile created or edited`.

**Comment by AllanBallester** [comment]
@pel-daniel 🙏again for yesterday !!!
