### ISSUE TITLE
Profile cards - Last modified the XX

### ISSUE THREAD

**Issue by AllanBallester** [AllanBallester/RiSE#80]

**Comment by AllanBallester** [comment]
<img width="1320" alt="capture d ecran 2017-12-16 a 17 38 25" src="https://user-images.githubusercontent.com/17672429/34072451-f64f96f2-e287-11e7-840c-0c4d3bc8be0b.png">


If "Last modified X days/minutes" the Users will not play treasure chase but will go straight to the most actualised.

**Comment by AllanBallester** [comment]
Like this : 
<img width="300" alt="capture d ecran 2017-12-16 a 17 41 08" src="https://user-images.githubusercontent.com/17672429/34072473-52aac372-e288-11e7-968f-86794e291e66.png">

**Comment by AllanBallester** [comment]
<img width="536" alt="capture d ecran 2017-12-18 a 22 29 24" src="https://user-images.githubusercontent.com/17672429/34129038-f843a694-e442-11e7-83c5-8a007baa9c82.png">

@pel-daniel Why he's looking for a translation while the time ago ?

**Comment by pel-daniel** [comment]
We can fix that by adding this gem https://github.com/svenfuchs/rails-i18n to the gemfile. Just copy the line that corresponds to the version of rails you're using

**Comment by AllanBallester** [comment]
<img width="491" alt="capture d ecran 2017-12-20 a 12 21 09" src="https://user-images.githubusercontent.com/17672429/34204814-676dc3b8-e580-11e7-8d13-e5dc3bfb6752.png">

<img width="950" alt="capture d ecran 2017-12-20 a 12 21 15" src="https://user-images.githubusercontent.com/17672429/34204816-6ac46a6c-e580-11e7-892b-641054084792.png">

I get 2.3.4 then I refer to the 2nd screenshot which specify for the 2.X versions.
But it seems to be what we did the manual installation : 
<img width="1378" alt="capture d ecran 2017-12-20 a 12 27 45" src="https://user-images.githubusercontent.com/17672429/34205055-3d2f2eb0-e581-11e7-85f9-c9afc20752ac.png">

What is missing Master Jedi @pel-daniel ?

**Comment by AllanBallester** [comment]
What I do not understand if that it's looking for a translation when it's ruby code.
If you got 15 min today tranquilo we kill that !!

<img width="846" alt="capture d ecran 2017-12-20 a 12 40 16" src="https://user-images.githubusercontent.com/17672429/34205523-06941684-e583-11e7-9a68-7b64ca4d4b40.png">

**Comment by pel-daniel** [comment]
The rails version of the project is `5.0.5`.

So add to the Gemfile:
```
gem 'rails-i18n', '~> 5.0.0'
```
And then run `bundle install` in the terminal.

**Comment by AllanBallester** [comment]
<img width="409" alt="capture d ecran 2017-12-20 a 17 54 52" src="https://user-images.githubusercontent.com/17672429/34218623-f70c5b0a-e5ae-11e7-820a-1616183c59c7.png">

May we call each other 2 min ?

**Comment by pel-daniel** [comment]
Just add that line to the file `Gemfile`. If doesn't work we can do it together.

**Comment by AllanBallester** [comment]
Que idiota ..
